let player_names = [
    "Marcos",
    "Haley",
    "Dahlia",
    "Kadyn",
    "Kevin",
    "Jessie",
    "Harrison",
    "Ali",
    "Fatima",
    "Cedric",
    "Raven",
    "Memphis",
    "Ansley",
    "Antoine",
    "Alan",
    "Van",
    "Arely",
    "Hailee",
    "Heather",
    "Brendan",
    "Bo",
    "Cory",
    "Holly",
    "Alexandra",
    "Hugo",
    "Maria",
    "Alec",
    "Abagail",
    "Meghan",
    "Kiera",
    "Lorelai",
    "Zoie",
    "Cash",
    "Cassidy",
    "Ayla",
    "Catherine",
    "Kelsey",
    "Sophie",
    "Margaret",
    "Madilynn",
    "Jordan",
    "Janiya",
    "Dulce",
    "Athena",
    "Cedric",
    "Zaniyah",
    "Rogelio",
    "Brent",
    "Irvin",
    "Edgar",
    "Reagan",
    "Ashleigh",
    "Charlotte",
    "Emiliano",
    "Devan",
    "Cara",
    "Heaven",
    "Addisyn",
    "Donna",
    "Diya",
    "Chana",
    "Alannah",
    "Landon",
    "Camryn",
    "Jade",
    "Allie",
    "Kinsley",
    "Arthur",
    "Barbara",
    "Dillon",
    "Katie",
    "Vicente",
    "Tamia",
    "Cullen",
    "Julissa",
    "Marquis",
    "Lyla",
    "Timothy",
    "Jayden",
    "Nehemiah",
    "Denzel",
    "Dwayne",
    "Giovanna",
    "Danna",
    "Audrina",
    "Hanna",
    "Jacey",
    "Destiny",
    "Deandre",
    "Damaris",
    "Nathan",
    "Colby",
    "Rayne",
    "Kayley",
    "Xavier",
    "Teresa",
    "Barrett",
    "Danika",
    "Campbell",
    "Cheyenne"
];

let bunny_names = [
    "Thumper",
    "Brer Rabbit",
    "White Rabbit",
    "March Hare",
    "Skippy",
    "Sis",
    "Tagalong",
    "Mother Rabbit",
    "Fun Bun",
    "Judy Hopps",
    "Bonnie Hopps",
    "Stu Hopps",
    "Lucky Jack",
    "Lilo and Twitch",
    "StellaLou",
    "Rabbit",
    "Oswald the Lucky",
    "Max Hare",
    "Clover",
    "Peter",
    "Flopsy",
    "Mopsy",
    "Cottontail",
    "Josephine",
    "Benjamin",
    "Mr. Bouncer",
    "Nutbrown Hare",
    "Velveteen",
    "Babbity Rabbity",
    "Bunnicula",
    "Miffy",
    "Captain Carrot",
    "Hoppy the Marvel Bunny",
    "Rabbid",
    "Honey Bunny",
    "Mr. Bun",
    "Bianca",
    "Miyamoto Usagi",
    "Hodge-Podge",
    "Jazz Jackrabbit",
    "Spaz Jackrabbit",
    "Lori Jackrabbit",
    "Bucky O'Hare",
    "Cutey Bunny",
    "Meadow",
    "Daisy",
    "Lavender",
    "Camellia",
    "Lilac",
    "April",
    "May",
    "June",
    "Bloom",
    "Spring Forward",
    "Blossom",
    "Lily",
    "Tulip",
    "Wildflower",
    "Daffodil",
    "Marigold",
    "Wisteria",
    "Thistle",
    "Primrose",
    "Harebell",
    "Poppy",
    "Violet",
    "Black-eyed Susan",
    "Chicory",
    "Bugs",
    "Lola",
    "Buster",
    "Babs",
    "Max",
    "Ruby",
    "Crusader",
    "Benny Rabbit",
    "Angel",
    "Bean",
    "Bing",
    "Flop",
    "Buster Baxter",
    "Bionic Bunny",
    "Dark Bunny",
    "Emily",
    "Swift Heart",
    "Ricochet",
    "Cuddles",
    "Incisor Gadget",
    "Tweak",
    "Bunnie Rabbot",
    "Mr. Bunny Rabbit",
    "Roger Rabbit",
    "Jessica Rabbit",
    "E.B.",
    "Fred O'Hare",
    "Easter Bunny",
    "Frank",
    "Hutch",
    "Were-Rabbit",
    "Snowball",
    "Hoptimus Prime",
    "Robohop",
    "Rabbit of Caerbannog",
    "Hoppy Gilmore",
    "Obi-Bun Kenobi",
    "Luke Skyhopper",
    "Forrest Jump",
    "Hare E. Potter",
    "Energizer",
    "Duracell",
    "Cadbury",
    "Yoyo",
    "Nesquik",
    "Trix",
    "Hazel",
    "Bigwig",
    "Fiver",
    "Blackberry",
    "Bluebell",
    "Strawberry",
    "Buckthorn",
    "Hawkbit",
    "Dandelion",
    "Silver",
    "Pipkin",
    "Speedwell",
    "Acorn",
    "Holly",
    "Chervil",
    "Hyzenthlay",
    "Vilthuril",
    "Thethuthinnang",
    "Thrayonlosa",
    "Nelthilta",
    "Blackavar",
    "General Woundwort",
    "Captain Campion",
    "Snowdrop",
    "Vervain",
    "El-ahrairah",
    "Carrot Top",
    "Marlon Bundo",
    "Sir Anthony Hopkins",
    "Scarlett Jumphansson",
    "Rabbit Pattinson",
    "Audrey Hopburn",
    "Marilyn Bunroe",
    "Dennis Hopper",
    "Jumpfrey Bogart",
    "Warren Beatty",
    "Drew Bunnymore",
    "Antonio Bunderas",
    "Dustin Hopman",
    "Gisele Bunnychen",
    "Leporidae",
    "Whiskers",
    "Buck",
    "Doe",
    "Coney",
    "Fuzzy",
    "Nibbles",
    "Buzz",
    "Binky",
    "Scamper",
    "Frolic",
    "Bonbon",
    "Rabbit Ears",
    "Quick Buck",
    "Hopscotch",
    "Furball",
    "Big Softie",
    "Rain Cloud",
    "Hoppy Camper",
    "Cumulo Nibbles",
    "Hoppy-go-lucky",
    "Jump 4 Joy",
    "Quiksilver",
    "Bonkers ",
    "Captain Fluffytail",
    "B-Rex",
    "Hoppertunity Knox",
    "Carrot Breath",
    "Sunday Bunday",
    "Chubby Bunny",
    "Flip Flop",
    "Hoppy birthday",
    "Little Bunny Foo Foo",
    "My Bunny Valentine",
    "Hip Hop",
    "Lady Antebunnum",
    "Childish Bunbino",
    "Jack Rabbit",
    "Bunny Cash",
    "Bun Jovi",
    "Smashing Jumpkins",
    "Eddie Rabbitt",
    "Iggy Hop",
    "Sir Hops-a-Lot",
    "Rabbit Heart",
    "Taylor Swift",
    "Bunny Holly",
    "Lindy Hop",
    "Ginger",
    "Cinnamon",
    "Pepper",
    "Vanilla",
    "Sugar",
    "Cocoa",
    "Nutmeg",
    "Clove",
    "Basil",
    "Anise",
    "Caraway",
    "Rosemary",
    "Coriander",
    "Paprika",
    "Sage",
    "Cotton Candy",
    "Fluffernutter",
    "Chestnut",
    "Cinnabun",
    "Sweetheart",
    "Darling",
    "Baby",
    "Snuggles",
    "Heavenly",
    "Lovely",
    "Pumpkin",
    "Treasure",
    "Cupcake",
    "Precious",
    "Sunshine",
    "Buttercup",
    "Spot",
    "Freckles",
    "Smokey",
    "Tuxedo",
    "State",
    "Pebbles",
    "Socks",
    "Patches",
    "Sandy",
    "Calico",
    "Stripes",
    "Dotty",
    "Nosey",
    "Shadow",
    "Dusty",
    "Speckles",
    "Dipper",
    "Mittens",
    "Splatter",
    "Hoppacrates",
    "Atilla the Bun",
    "Nicolaus Hopernicus",
    "Napoleon Bunaparte",
    "George Hoppington",
    "Bunjamin Franklin",
    "Thomas Jumperson",
    "Abrahare Lincoln",
    "Bunny Roosevelt",
    "Dwight D. Eisenhopper",
    "John F. Bunnedy",
    "George W. Bushytail",
    "Donald Jump",
    "Steven Hopping",
    "Grace Hopper",
    "Mocha",
    "Cappuccino",
    "Macchiato",
    "Espresso",
    "Hazelnut",
    "Caramel",
    "Blonde",
    "Latte",
    "Coffee",
    "Hare of Inaba",
    "Al-Mir’aj",
    "Jackalope",
    "Jade Rabbit",
    "Skvader",
    "Wenet",
    "Nanabozho",
    "Cabbit",
    "Wolpertinger",
    "Milk Rabbit",
    "Magic",
    "Conejo",
    "Kaninchen",
    "Coniglio",
    "Kani",
    "Królik",
    "Lapin",
    "Thỏ",
    "Lepus",
    "Usagi",
    "Konijn"
];

let bear_names = [
    "Mr. Bear",
    "Angel",
    "Sprinkles",
    "Teddy",
    "Cuddles",
    "Lovebug",
    "Baby Bear",
    "Bootsy",
    "Bella",
    "Cuddlebug",
    "Bear Hugz",
    "Winnie",
    "Buttercup",
    "Snuggabear",
    "Bubsy",
    "Sobig",
    "Fuzzy Wuzzy",
    "Sugar",
    "Honey",
    "Snuggles",
    "Grizzlee",
    "Racer",
    "Camper",
    "Rocky",
    "Claws",
    "Scout",
    "Armor",
    "Fisher",
    "Franklin",
    "Scooter",
    "Mr. Goodbear",
    "Skylar",
    "Baloo",
    "Hiker",
    "Penny",
    "Theodore",
    "Barley",
    "Penelope",
    "Horace",
    "Trooper",
    "Pookie",
    "Ding Dong",
    "Mr. Hugglesworth",
    "Bearly Chubs",
    "Rawr",
    "Bozo",
    "Mr. Fluffles",
    "Lazy Bear",
    "Ted",
    "Guardian",
    "Mrs. Kisses",
    "Sunny",
    "Ron",
    "Chubby",
    "Napolean",
    "Yolanda",
    "Beary Potter",
    "Beethoven",
    "Bob",
    "Frankenstein"
];

let dragon_names = [
    "Falkor",
    "Saphira",
    "Mushu",
    "Toothless",
    "Fin Fang Foom",
    "Draco",
    "Smaug",
    "Elliot",
    "Puff",
    "Apalala",
    "Apep",
    "Apophis",
    "Askook",
    "Astarot",
    "Attor",
    "Ator",
    "Chua",
    "Coatl",
    "Dracul",
    "Drago",
    "Drakon",
    "Ehecatl",
    "Fafnir",
    "Glaurung",
    "Herensuge",
    "Iormungand",
    "Knucker",
    "Ladon",
    "Leviathan",
    "Longwei",
    "Nagendra",
    "Nidhogg",
    "Nilakanta",
    "Ophiuchus",
    "Ormarr",
    "Ormr",
    "Orochi",
    "Pendragon",
    "Pythagoras",
    "Pythios",
    "Quetzalcoatl",
    "Ryuu",
    "Samael",
    "Shesha",
    "Tatsuo",
    "Tatsuya",
    "Tezcacoatl",
    "Uruloki",
    "Uther",
    "Vasuki",
    "Veles",
    "Viper",
    "Vritra",
    "Adalinda",
    "Amelinda",
    "Annabelinda",
    "Belinda",
    "Chumana",
    "Chusi",
    "Hydra",
    "Linda",
    "Malinda",
    "Kaida",
    "Medousa",
    "Melusine",
    "Shuman",
    "Tanis",
    "Tanit",
    "Tiamat",
    "Drake",
    "Brantley",
    "Ryoko",
    "Arrow",
    "Tatsuya",
    "Pachua",
    "Chance",
    "Aidan",
    "Blaze",
    "Xiuhcoatl",
    "Absinthe",
    "Blizzard",
    "Chilalea",
    "Daenerys",
    "Eisdrachen",
    "Eirwen",
    "Etoirir",
    "Frostine",
    "Lodsmok",
    "Nidhogg",
    "Nieves",
    "Sarmite",
    "Snowstorm",
    "Valkoinen",
    "Watatsumi",
    "Yukiharu",
    "Yukina",
    "Starblaze",
    "Reombarth",
    "Blaze",
    "Jergintarth",
    "Unniass",
    "Archion",
    "Abeloth",
    "Bazzoit",
    "Zysyss",
    "Frerryry",
    "Rex",
    "Cedric",
    "Trixie",
    "Sydney",
    "Harper",
    "Opal",
    "Merlin",
    "Fluffy",
    "Beardie",
    "Fabio",
    "Durian",
    "Pickles",
    "Sugar",
    "Cricket",
    "Pebble",
    "Sprinkles",
    "Inferno",
    "Smokey",
    "Aiden",
    "Cadmus",
    "Ehecatl",
    "Fafnir",
    "Kai",
    "Nithe",
    "Ormr",
    "Brenna",
    "Edna",
    "Kaida",
    "Mindy",
    "Scylla",
    "Tanwen",
    "Uwibami",
    "Wyvern",
    "Antoinette",
    "Absinthe",
    "Rex",
    "Sobek",
    "Ebeneezer",
    "Elmo",
    "Eponine",
    "Bonaventure",
    "Briony",
    "Hamnet",
    "Hedwig",
    "Dino",
    "Glismoda",
    "Doryu",
    "Ejder",
    "Fraener",
    "Jiao-long",
    "Ju-long",
    "Khuzaimah",
    "Libelle",
    "Deadheart",
    "Druk",
    "Ghidorah",
    "Helios",
    "Knucker",
    "Nocturne",
    "Oboth",
    "Shenron",
    "Irad",
    "Melly",
    "Syrax",
    "Yang",
    "Akhekh",
    "Campe",
    "Heperios",
    "Ketos",
    "Kur",
    "Draigoch",
    "Alduin",
    "Enywas",
    "Marun",
    "Naga",
    "Singe",
    "Synn",
    "Corypheus",
    "Chinglai",
    "Brugmo",
    "Astrite",
    "Eltanin",
    "Jeysar",
    "Kagero",
    "Laurana",
    "Leliana",
    "Longxing",
    "Meguro",
    "Ryoma",
    "Ryuhei",
    "Sarkan",
    "Seiryu",
    "Shulgan",
    "Solontu",
    "Uryuu",
    "Yongjin",
    "Zilong"
];

let ghost_names = [
    "Madam Koi Koi",
    "Obambo",
    "Hungry ghost",
    "Mogwai",
    "Vengeful ghost",
    "Wangliang",
    "Yaoguai",
    "Ayakashi",
    "Chōchin-obake",
    "Funayūrei",
    "Gashadokuro",
    "Goryō",
    "Hitodama",
    "Ikiryō",
    "Inugami",
    "Kuchisake-onna",
    "Mononoke",
    "Mujina",
    "Noppera-bō",
    "Obake",
    "Ochimusha",
    "Onryō",
    "Raijū",
    "Shikigami",
    "Shinigami",
    "Shirime",
    "Shiryō",
    "Tsukumogami",
    "Ubume",
    "Umibōzu",
    "Yōkai",
    "Yōsei",
    "Yuki-onna",
    "Yūrei",
    "Nale Ba",
    "Pūtam",
    "Pishacha",
    "Preta",
    "Naagin",
    "Daayan",
    "Chetkin",
    "Churel",
    "Challava",
    "Yakshini",
    "Vetala",
    "Preta",
    "Pisacha",
    "Yaksha",
    "Kumbanda",
    "Mara",
    "Holnab",
    "Maha Sohona",
    "Riri yaka",
    "Kola Sanni Yaka",
    "Gara yaka",
    "Kalu Kumara",
    "Suniyam yaka",
    "Devil Bird",
    "Bodilima",
    "Asura",
    "Mala preta",
    "Zombie",
    "Banjhakri",
    "Banjhakrini",
    "Kichkandi",
    "Raakebhoot",
    "Churel",
    "Pichal Peri",
    "Hantu Air",
    "Hantu Raya",
    "Jenglot",
    "Kuntilanak",
    "Matianak",
    "Pontianak",
    "Langsuyar",
    "Leyak",
    "Orang Minyak",
    "Pelesit",
    "Pocong",
    "Penanggalan",
    "Sundel bolong",
    "Toyol",
    "Nat",
    "Peik-ta",
    "Thayé",
    "Aswang",
    "Manananggal",
    "Tiyanak",
    "Kapre",
    "TikTik",
    "Krasue",
    "Krahang",
    "Mae Nak",
    "Nang Tani",
    "Nang Takian",
    "Phi Pop",
    "Mamdo Bhoot",
    "Petni",
    "Shakchunni",
    "Meccho Bhoot",
    "Geccho Bhoot",
    "Daynii",
    "Doitoo",
    "Pishach",
    "Bhrommo Doitto",
    "Kana Bhola",
    "Rakkhosh",
    "Khuqqush",
    "Nishi",
    "Dayniburi",
    "Jukkho",
    "Dybbuk",
    "Shedim"
];

let chicken_names = ["Curry",
    "Daisy",
    "Noodle",
    "Frittata",
    "Kung",
    "Pao",
    "Margaret Hatcher",
    "Marsala",
    "Meryl",
    "Cheep",
    "Nugget",
    "Peep",
    "Piccata",
    "Rosie",
    "Ruby",
    "Snowball",
    "Tandoori",
    "Teriyaki",
    "Yolkahontas",
    "Benedict",
    "Buffalo",
    "Cashew",
    "Colonel Sanders",
    "Crispy",
    "Curry",
    "Custard",
    "Divan",
    "Drumstick",
    "Dumpling",
    "Egg Nog",
    "Frittata",
    "Hot Wing",
    "Kabob",
    "Kung Pao",
    "Marsala",
    "Noodle",
    "Nugget",
    "Omelet",
    "Parmesan",
    "Patty",
    "Peep",
    "Piccata",
    "Pot Pie",
    "Sesame",
    "Tandoori",
    "Tender",
    "Teriyaki",
    "Quiche",
    "Winner Winner (Chicken Dinner)",
    "Albert Eggstein",
    "Amelia Egghart",
    "Attila the Hen",
    "Chick Jagger",
    "Cluck Kent",
    "Cluck Norris",
    "Cluck Rogers",
    "Hen Solo",
    "Margaret Hatcher",
    "Meryl Cheep",
    "Obi Wan Henobi",
    "Princess",
    "Lay-a",
    "Sir Clucks-A-Lot",
    "Tyrannosaurus Pecks",
    "Yolkahontas",
    "Yolko Ono",
    "Anna",
    "Elsa",
    "Bonnie",
    "Clyde",
    "Cookies",
    "Cream",
    "Eeny",
    "Meeny",
    "Miny",
    "Moe",
    "Flora",
    "Fauna",
    "Merryweather",
    "Hansel",
    "Gretel",
    "Laverne",
    "Shirley",
    "Lucy",
    "Desi",
    "Parsley",
    "Sage",
    "Rosemary",
    "Thyme",
    "Romeo",
    "Juliet",
    "Salt",
    "Pepper",
    "Snap",
    "Crackle",
    "Pop",
    "Sonny",
    "Cher",
    "Sugar",
    "Spice",
    "Thelma",
    "Louise",
    "Yin",
    "Yang",
    "Clementine",
    "Clover",
    "Daisy",
    "Lacey",
    "Lily",
    "Opal",
    "Pearl",
    "Price",
    "Princess",
    "Rosie",
    "Ruby",
    "Snowball",
    "Sugar",
    "Tinkerbell"
];

let dog_names = ["Abby",
    "Abe",
    "Addie",
    "Abbott",
    "Alexis",
    "Ace",
    "Alice",
    "Aero",
    "Allie",
    "Aiden",
    "Alyssa",
    "AJ",
    "Amber",
    "Albert",
    "Angel",
    "Alden",
    "Anna",
    "Alex",
    "Annie",
    "Alfie",
    "Ariel",
    "Alvin",
    "Ashley",
    "Amos",
    "Aspen",
    "Andy",
    "Athena",
    "Angus",
    "Autumn",
    "Apollo",
    "Ava",
    "Archie",
    "Avery",
    "Aries",
    "Baby",
    "Artie",
    "Bailey",
    "Ash",
    "Basil",
    "Austin",
    "Bean",
    "Axel",
    "Bella",
    "Bailey",
    "Belle",
    "Bandit",
    "Betsy",
    "Barkley",
    "Betty",
    "Barney",
    "Bianca",
    "Baron",
    "Birdie",
    "Baxter",
    "Biscuit",
    "Bear",
    "Blondie",
    "Beau",
    "Blossom",
    "Benji",
    "Bonnie",
    "Benny",
    "Brandy",
    "Bentley",
    "Brooklyn",
    "Billy",
    "Brownie",
    "Bingo",
    "Buffy",
    "Blake",
    "Callie",
    "Blaze",
    "Camilla",
    "Blue",
    "Candy",
    "Bo",
    "Carla",
    "Boomer",
    "Carly",
    "Brady",
    "Carmela",
    "Brody",
    "Casey",
    "Brownie",
    "Cassie",
    "Bruce",
    "Chance",
    "Bruno",
    "Chanel",
    "Brutus",
    "Chloe",
    "Bubba",
    "Cinnamon",
    "Buck",
    "Cleo",
    "Buddy",
    "Coco",
    "Buster",
    "Cookie",
    "Butch",
    "Cricket",
    "Buzz",
    "Daisy",
    "Cain",
    "Dakota",
    "Captain",
    "Dana",
    "Carter",
    "Daphne",
    "Cash",
    "Darla",
    "Casper",
    "Darlene",
    "Champ",
    "Delia",
    "Chance",
    "Delilah",
    "Charlie",
    "Destiny",
    "Chase",
    "Diamond",
    "Chester",
    "Diva",
    "Chewy",
    "Dixie",
    "Chico",
    "Dolly",
    "Chief",
    "Duchess",
    "Chip",
    "Eden",
    "CJ",
    "Edie",
    "Clifford",
    "Ella",
    "Clyde",
    "Ellie",
    "Coco",
    "Elsa",
    "Cody",
    "Emma",
    "Colby",
    "Emmy",
    "Cooper",
    "Eva",
    "Copper",
    "Faith",
    "Damien",
    "Fanny",
    "Dane",
    "Fern",
    "Dante",
    "Fiona",
    "Denver",
    "Foxy",
    "Dexter",
    "Gabby",
    "Diego",
    "Gemma",
    "Diesel",
    "Georgia",
    "Dodge",
    "Gia",
    "Drew",
    "Gidget",
    "Duke",
    "Gigi",
    "Dylan",
    "Ginger",
    "Eddie",
    "Goldie",
    "Eli",
    "Grace",
    "Elmer",
    "Gracie",
    "Emmett",
    "Greta",
    "Evan",
    "Gypsy",
    "Felix",
    "Hailey",
    "Finn",
    "Hannah",
    "Fisher",
    "Harley",
    "Flash",
    "Harper",
    "Frankie",
    "Hazel",
    "Freddy",
    "Heidi",
    "Fritz",
    "Hershey",
    "Gage",
    "Holly",
    "George",
    "Honey",
    "Gizmo",
    "Hope",
    "Goose",
    "Ibby",
    "Gordie",
    "Inez",
    "Griffin",
    "Isabella",
    "Gunner",
    "Ivy",
    "Gus",
    "Izzy",
    "Hank",
    "Jackie",
    "Harley",
    "Jada",
    "Harvey",
    "Jade",
    "Hawkeye",
    "Jasmine",
    "Henry",
    "Jenna",
    "Hoss",
    "Jersey",
    "Huck",
    "Jessie",
    "Hunter",
    "Jill",
    "Iggy",
    "Josie",
    "Ivan",
    "Julia",
    "Jack",
    "Juliet",
    "Jackson",
    "Juno",
    "Jake",
    "Kali",
    "Jasper",
    "Kallie",
    "Jax",
    "Karma",
    "Jesse",
    "Kate",
    "Joey",
    "Katie",
    "Johnny",
    "Kayla",
    "Judge",
    "Kelsey",
    "Kane",
    "Khloe",
    "King",
    "Kiki",
    "Kobe",
    "Kira",
    "Koda",
    "Koko",
    "Lenny",
    "Kona",
    "Leo",
    "Lacy",
    "Leroy",
    "Lady",
    "Levi",
    "Layla",
    "Lewis",
    "Leia",
    "Logan",
    "Lena",
    "Loki",
    "Lexi",
    "Louie",
    "Libby",
    "Lucky",
    "Liberty",
    "Luke",
    "Lily",
    "Marley",
    "Lizzy",
    "Marty",
    "Lola",
    "Maverick",
    "London",
    "Max",
    "Lucky",
    "Maximus",
    "Lulu",
    "Mickey",
    "Luna",
    "Miles",
    "Mabel",
    "Milo",
    "Mackenzie",
    "Moe",
    "Macy",
    "Moose",
    "Maddie",
    "Morris",
    "Madison",
    "Murphy",
    "Maggie",
    "Ned",
    "Maisy",
    "Nelson",
    "Mandy",
    "Nero",
    "Marley",
    "Nico",
    "Matilda",
    "Noah",
    "Mattie",
    "Norm",
    "Maya",
    "Oakley",
    "Mia",
    "Odie",
    "Mika",
    "Odin",
    "Mila",
    "Oliver",
    "Miley",
    "Ollie",
    "Millie",
    "Oreo",
    "Mimi",
    "Oscar",
    "Minnie",
    "Otis",
    "Missy",
    "Otto",
    "Misty",
    "Ozzy",
    "Mitzi",
    "Pablo",
    "Mocha",
    "Parker",
    "Molly",
    "Peanut",
    "Morgan",
    "Pepper",
    "Moxie",
    "Petey",
    "Muffin",
    "Porter",
    "Mya",
    "Prince",
    "Nala",
    "Quincy",
    "Nell",
    "Radar",
    "Nellie",
    "Ralph",
    "Nikki",
    "Rambo",
    "Nina",
    "Ranger",
    "Noel",
    "Rascal",
    "Nola",
    "Rebel",
    "Nori",
    "Reese",
    "Olive",
    "Reggie",
    "Olivia",
    "Remy",
    "Oreo",
    "Rex",
    "Paisley",
    "Ricky",
    "Pandora",
    "Rider",
    "Paris",
    "Riley",
    "Peaches",
    "Ringo",
    "Peanut",
    "Rocco",
    "Pearl",
    "Rockwell",
    "Pebbles",
    "Rocky",
    "Penny",
    "Romeo",
    "Pepper",
    "Rosco",
    "Phoebe",
    "Rudy",
    "Piper",
    "Rufus",
    "Pippa",
    "Rusty",
    "Pixie",
    "Sam",
    "Polly",
    "Sammy",
    "Poppy",
    "Samson",
    "Precious",
    "Sarge",
    "Princess",
    "Sawyer",
    "Priscilla",
    "Scooby",
    "Raven",
    "Scooter",
    "Reese",
    "Scout",
    "Riley",
    "Scrappy",
    "Rose",
    "Shadow",
    "Rosie",
    "Shamus",
    "Roxy",
    "Shiloh",
    "Ruby",
    "Simba",
    "Sadie",
    "Simon",
    "Sage",
    "Smoky",
    "Sally",
    "Snoopy",
    "Sam",
    "Sparky",
    "Samantha",
    "Spencer",
    "Sammie",
    "Spike",
    "Sandy",
    "Spot",
    "Sasha",
    "Stanley",
    "Sassy",
    "Stewie",
    "Savannah",
    "Storm",
    "Scarlet",
    "Taco",
    "Shadow",
    "Tank",
    "Sheba",
    "Taz",
    "Shelby",
    "Teddy",
    "Shiloh",
    "Tesla",
    "Sierra",
    "Theo",
    "Sissy",
    "Thor",
    "Sky",
    "Titus",
    "Smokey",
    "TJ",
    "Snickers",
    "Toby",
    "Sophia",
    "Trapper",
    "Sophie",
    "Tripp",
    "Star",
    "Tucker",
    "Stella",
    "Tyler",
    "Sugar",
    "Tyson",
    "Suki",
    "Vince",
    "Summer",
    "Vinnie",
    "Sunny",
    "Wally",
    "Sweetie",
    "Walter",
    "Sydney",
    "Watson",
    "Tasha",
    "Willy",
    "Tessa",
    "Winston",
    "Tilly",
    "Woody",
    "Tootsie",
    "Wrigley",
    "Trixie",
    "Wyatt",
    "Violet",
    "Yogi",
    "Willow",
    "Yoshi",
    "Winnie",
    "Yukon",
    "Xena",
    "Zane",
    "Zelda",
    "Zeus",
    "Zoe",
    "Ziggy"
];